# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='likeuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 30, 19, 45, 47, 839325)),
        ),
    ]
