# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160525_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='article.Tag', verbose_name='\u0422\u0435\u0433\u0438'),
        ),
    ]
