# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 18:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0005_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 3, 15, 0, 46, 5, 490074))),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'articles_user',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ManyToManyField(through='article.LikeUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
