# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20160315_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeuser',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='likeuser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='likeuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 0, 47, 21, 415313)),
        ),
    ]
